eptrlist.h: Fix compilation error on unqualified 'insert' Fixes the following error in upstream OE:
../lib/base/eptrlist.h: In instantiation of 'ePtrList<T>::iterator ePtrList<T>::insert_in_order(T*) [with T = eTimer]':
base/ebase.cpp:320:32:   required from here
../lib/base/eptrlist.h:178:96: error: 'insert' was not declared in this scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   return insert( std::lower_bound( std::list<T*>::begin(), std::list<T*>::end(), e, less()), e );
../lib/base/eptrlist.h:178:96: note: declarations in dependent base 'std::list<eTimer*, std::allocator<eTimer*> >' are not found by unqualified lookup
../lib/base/eptrlist.h:178:96: note: use 'this->insert' instead